### Get all parking spaces
GET http://localhost:5000/app

### Get all visitors
GET http://localhost:5000/app/visitors

### Get visitor by license plate
GET http://localhost:5000/app/visitors/abc123

### Add the number of parking spaces
POST http://localhost:5000/app/spaces
Content-Type: application/json

{
  "quantity": 5
}

### Add new visitor
POST http://localhost:5000/app/visitors
Content-Type: application/json

{
  "licensePlate": "ABC123",
  "make": "Toyota",
  "model": 2015
}

### Delete a visitor
DELETE http://localhost:5000/app/visitors/DEF456
